params:
  epochs: 3
  batch_size: 32
  no_of_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  early_stopping_patience: 5


artifacts:   
  artifacts_dir: artifacts
  model_dir: model
  plot_dir: plots
  checkpoint_dir: checkpoints
  model_name: model.h5
  plot_name: accuracy.png
  ckpt_dir: modelckpt
  ckpt_name: model_ckpt.h5

logs:
  logs_dir: logs_dir
  general_logs: general_logs
  tensorboard_logs: tensorboard_logs